<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('flight_bookings', function (Blueprint $table) {
            $table->id();
            $table->string('booking_no')->nullable()->comment('Generated by Our System');
            $table->unsignedBigInteger('booked_by')->nullable()->comment('User Table ID');
            $table->double('b2b_comission')->comment('In Percentage')->default(0);

            $table->string('pnr_id')->nullable()->comment('From Sabre');
            $table->string('booking_id')->nullable()->comment('From Sabre');
            $table->string('ticket_id')->nullable()->comment('From Sabre');

            $table->string('gds')->nullable();
            $table->string('gds_unique_id')->nullable()->comment('e.g. PCC');

            $table->string('traveller_name')->nullable();
            $table->string('traveller_email')->nullable()->comment('For Sending Email');
            $table->string('traveller_contact')->nullable()->comment('For Sending SMS');

            $table->string('departure_date')->nullable();
            $table->string('departure_location')->nullable();
            $table->string('arrival_location')->nullable();
            $table->string('governing_carriers')->nullable();
            $table->string('adult')->nullable();
            $table->string('child')->nullable();
            $table->string('infant')->nullable();
            $table->double('base_fare_amount')->nullable();
            $table->double('total_tax_amount')->nullable();
            $table->double('total_fare')->nullable();
            $table->string('currency')->nullable();

            $table->string('last_ticket_datetime')->nullable();
            $table->string('booking_cancelled_at')->nullable();
            $table->string('ticket_issued_at')->nullable();
            $table->string('ticket_cancelled_at')->nullable();

            $table->longText('booking_response')->comment("Directly From API (Unfiltered)")->nullable();

            $table->tinyInteger('status')->default(1)->comment('1=>Booking Done; 2=>Ticketing Done; 3=>Booking Cancelled; 4=>Ticket Cancelled');
            $table->tinyInteger('is_live')->comment('1=>Live Booking; 0=>Sandbox Booking')->nullable();

            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('flight_bookings');
    }
};
